In [2]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7,8]])
print("2D Array:\n", array_2d)

# Creating a 3D NumPy array
array_3d = np.array([[[1, 2],[3,4]],[[5, 6],[7,8]]])
print("3D Array:\n", array_3d)




1D Array: [1 2 3 4]
2D Array:
 [[1 2 3 4]
 [5 6 7 8]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
array_3d.dtype

dtype('int64')

In [19]:
array1d = np.array([1,2,3,4,5])
print(array_1d)
# array1d.shape
array1d.size
array1d.dtype

[1 2 3 4]


dtype('int64')

In [20]:
array2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)
array2d.shape
array2d.size
array2d.dtype

[[1 2 3 4]
 [5 6 7 8]]


dtype('int64')

In [18]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(float)
print(newarr)

[1.1 2.1 3.1]


In [25]:
array_2d3d = np.array([
                        [[1, 2, 3, 4], 
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]
                        ],
                       
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                      ])
print(array_2d3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
array_2d3d[0,1,2] # 0-layer, 1- row, 2 column

np.int64(7)

In [ ]:
array_2d3d[0,2] # to get 3rd row 

array([ 9, 10, 11, 12])

In [29]:
array_2d3d[0,0:2,0]

array([1, 5])

In [ ]:
array_2d3d[0,:,0]  # : - all rows

array([1, 5, 9])

In [ ]:
array_2d3d[0,:,::2]  # ::2 from begiiing to the end bu skipping every other column

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [33]:
# Boolean indexing
array_2d3d[array_2d3d > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24])

In [35]:
arranged = np.arange(47,92,2)
print(arranged)

[47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91]


In [38]:
new = np.array(array_2d3d)
print(new)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
new[0,1] = [65,64,63,62] # to change values in a pecific place
new

array([[[ 1,  2,  3,  4],
        [65, 64, 63, 62],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [42]:
new[0,0] =99
new

array([[[99, 99, 99, 99],
        [65, 64, 63, 62],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [46]:
new[1,:2] = np.array([1,2]).reshape((2,1))
new

array([[[99, 99, 99, 99],
        [65, 64, 63, 62],
        [ 9, 10, 11, 12]],

       [[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [21, 22, 23, 24]]])

In [50]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [51]:
a+b

array([5, 7, 9])

In [52]:
a*b

array([ 4, 10, 18])

In [55]:
c = np.array([[1,2,3],
             [4,5,6]])

d = np.array([1,1,1])



In [56]:
c+d

array([[2, 3, 4],
       [5, 6, 7]])

In [6]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([7, 5, 1, 2, 4, 6, 3])

In [14]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[5, 6],
       [3, 4],
       [1, 2]])

In [15]:
# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


Example 1: Adding a Scalar to an Array

In [16]:
# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)


Original Array: [1 2 3]
After Adding 5: [6 7 8]


Example 2: Combining 1D and 2D Arrays

In [17]:

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


Example 3: Broadcasting Arrays with Different Shapes

In [18]:
# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


Example 4: Broadcasting Limitations

In [19]:
# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


Example 5: Multiplying Arrays of Different Dimensions

In [20]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


Array Aggregation: Sum, Mean, Min, Max

In [21]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


Reshaping array

In [22]:
# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
data = np.arange(1, 101).reshape(20, 5)
data

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])