 Exercise 1 : Array Creation and Manipulation

In [3]:
import numpy as np
array1d = np.arange(0,10)
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 Exercise 2 : Type Conversion and Array Operations

In [ ]:
list1 =[3.14, 2.17, 0, 1, 2]
new_array = np.array(list1).astype(int)
new_array

array([3, 2, 0, 1, 2])

Exercise 3 : Working with Multi-Dimensional Arrays

In [13]:
array_1 = np.arange(1,10)
reshaped = array_1.reshape(3,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [5]:

random_array = np.random.rand(4,5).round(2)
print(random_array)


[[0.03 0.73 0.57 0.85 0.62]
 [0.28 0.01 0.84 0.17 0.58]
 [0.21 0.23 0.05 0.11 0.96]
 [0.82 0.9  0.07 0.85 0.34]]


 Exercise 5 : Indexing Arrays

In [29]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1]

array([20, 21, 22, 23, 24])

Exercise 6 : Reversing elements

In [36]:
array2 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
array2[::-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 7 : Identity Matrix

In [37]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercise 8 : Simple Aggregate Funcs

In [55]:
array3 = np.full(10,4.5)
print(array3)
print("Sum:",array3.sum())
print("Average",array3.mean())

[4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5]
Sum: 45.0
Average 4.5


Exercise 9 : Create Array and Change its Structure

In [58]:
array4 = np.arange(1,21).reshape(4,5)
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Exercise 10 : Conditional Selection of Values

In [64]:
array5 = np.arange(1,10)
array5[0::2]

array([1, 3, 5, 7, 9])